const data = [
    {'assessment_id': 756416, 'id_no': 158002, 'sci_name': 'Cordia trichocladophylla', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2007.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.75, 'latitude': -10.05, 'img-url':'https://fm-digital-assets.fieldmuseum.org/169/860/BORA_cord_tric_bra_895958.jpg'},

 
    {'assessment_id': 756495, 'id_no': 158003, 'sci_name': 'Plumbago ciliata', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.25, 'latitude': -10.1666, 'img-url':NaN},


     {'assessment_id': 757412, 'id_no': 158021, 'sci_name': 'Tragia pogostemonoides', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2007.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.25, 'latitude': -6.8, 'img-url':NaN},


     {'assessment_id': 758841, 'id_no': 158053, 'sci_name': 'Ochna polyarthra', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.0333, 'latitude': -6.8333, 'img-url':'https://www.kew.org/herbcatimg/281336.jpg'},

 
     {'assessment_id': 759189, 'id_no': 158060, 'sci_name': 'Phyllanthus schliebenii', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2007.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.4, 'latitude': -9.9833,'img-url':'https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:898401-1/images'},


     {'assessment_id': 760778, 'id_no': 158098, 'sci_name': 'Ochna citrina', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.3666, 'latitude': -10.3,'img-url':NaN},

 
     {'assessment_id': 762967, 'id_no': 158149, 'sci_name': 'Impatiens saliensis', 'presence': 4, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Possibly Extinct', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 1932.0, 'longitude': 36.6833, 'latitude': -8.9666,'img-url':NaN},

 
     {'assessment_id': 763372, 'id_no': 158157, 'sci_name': 'Gutenbergia oppositifolia', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'East African Plant Red List Authority', 'yrcompiled': 2019.0, 'citation': 'IUCN', 'legend': 'Extant (resident)', 'subspecies': ' ', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 38.7, 'latitude': -6.4333, 'img-url':NaN},

 
  
      {'assessment_id': 763742, 'id_no': 158167, 'sci_name': 'Ochna schliebenii', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.75, 'latitude': -10.05, 'img-url':'https://plants.jstor.org/fsi/img/size1/alukaplant/lisc/phase_01/lisc0000/lisc000920.jpg'},

 
      {'assessment_id': 765782, 'id_no': 158189, 'sci_name': 'Sphaeranthus cristatus', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'East African Plant Red List Authority', 'yrcompiled': 2019.0, 'citation': 'IUCN', 'legend': 'Extant (resident)', 'subspecies': ' ', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 38.5, 'latitude': -4.8333, 'img-url': 'https://plants.jstor.org/fsi/img/misc/plants/static_thumbs/flora_tropEA_icon96.jpg'},

 {'assessment_id': 767182, 'id_no': 158222, 'sci_name': 'Ochna braunii', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2008.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.25, 'latitude': -10.1666, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/ea/phase_01/ea0001/ea000002031.jpg'},

 
 {'assessment_id': 768885, 'id_no': 158253, 'sci_name': 'Impatiens humifusa', 'presence': 6, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2007.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Presence Uncertain', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 37.75, 'latitude': -6.8833, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/b/phase_01/b0000/b_10_0153320.jpg'},


 {'assessment_id': 768968, 'id_no': 158254, 'sci_name': 'Impatiens tricaudata', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2007.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 37.6333, 'latitude': -7.1333, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/lisc/phase_01/lisc0004/lisc000744.jpg'},

 {'assessment_id': 1407024, 'id_no': 173968, 'sci_name': 'Diospyros ketsensis', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'L. Faranirina', 'yrcompiled': 2018.0, 'citation': 'MBG', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'Madagascar', 'tax_comm': 'N/A', 'source': 'H. Perrier de la Bâthie 17785', 'basisofrec': 'N/A', 'event_year': 1926.0, 'longitude': 47.0166667, 'latitude': -17.75, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/p/phase_01/p0001/p00573541.jpg'},

 {'assessment_id': 1572734, 'id_no': 179256, 'sci_name': 'Orthosiphon scedastophyllus', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2011.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 1900.0, 'longitude': 39.3333, 'latitude': -9.75, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/bm/phase_01/bm0001/bm000910011.jpg'},


 {'assessment_id': 1573421, 'id_no': 179270, 'sci_name': 'Rhynchosia braunii', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2011.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 2012.0, 'longitude': 39.1666, 'latitude': -8.1333, 'img-url': NaN},

 {'assessment_id': 1575393, 'id_no': 179331, 'sci_name': 'Rhynchosia calobotrya', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2011.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 1935.0, 'longitude': 39.4833, 'latitude': -10.05, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/lisc/phase_01/lisc0006/lisc002276.jpg'},

 {'assessment_id': 1577250, 'id_no': 179398, 'sci_name': 'Phyllanthus rhizomatosus', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2010.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 37.5666, 'latitude': -6.0666, 'img-url': 'https://plants.jstor.org/fsi/img/size1/alukaplant/br/phase_01/br0003/br0000006243753.jpg'},

 {'assessment_id': 1581746, 'id_no': 179531, 'sci_name': 'Combretum lindense', 'presence': 1, 'origin': 1, 'seasonal': 1, 'compiler': 'IUCN SSC Eastern African Plant Red List Authority', 'yrcompiled': 2010.0, 'citation': 'IUCN SSC Eastern African Plant Red List Authority', 'legend': 'Extant (resident)', 'subspecies': 'N/A', 'subpop': 'N/A', 'dist_comm': 'N/A', 'island': 'N/A', 'tax_comm': 'N/A', 'source': 'N/A', 'basisofrec': 'N/A', 'event_year': 0.0, 'longitude': 39.2, 'latitude': -10.7166, 'img-url': 'https://plants.jstor.org/fsi/img/misc/plants/static_thumbs/flora_tropEA_icon96.jpg'}]

export default data;